name: Docker
run-name: Publish Docker tag
on: [push]
jobs:
  Publish-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the tagged Docker image
        working-directory: ./docker
        run: docker build -t tasky .